region = "sa-santiago-1"
tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaakdzlbkkale2guohrsmtg6ewml63ku3ra7my3zq2ctj3hk4etkwja"
customer_name = "fts"
vcn_dns_label = "oml"
instance_display_name = "omlapp"
subnet_cidr_block = "10.72.1.0/24"
